[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "groq>=0.4.0",
    "httpx>=0.28.1",
    "mcp>=1.1.1",
    "python-dotenv>=1.0.1",
]
